#!/usr/bin/env python3

import wheatley.main
import sys

# `[1:]` is apparently needed, because sys.argv[0] is the working file of the Python interpreter
# which `argparse.Parser.parse_args` does not want to see as an argument
args = sys.argv[1:]
stop_on_join_tower = False
server_mode = False

# If the user adds 'server-mode' to the command, run the server-mode main function, and remove the
# 'server-mode' argument
if len(args) > 0 and args[0] == "server-mode":
    args = args[1:]
    server_mode = True

if len(args) > 0 and args[0] == "integration-test":
    del args[0]
    stop_on_join_tower = True

main_function = wheatley.main.server_main if server_mode else wheatley.main.main
main_function(args, stop_on_join_tower)
