name: "Testing/Linting/Fuzzing"

on:
  pull_request:
    branches:
      - master
      - release/*
  push:
    branches:
      - master
      - release/*
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          pip3 install setuptools
          pip3 install -r requirements.txt
      - name: Run linter
        run: python3 -m pylint wheatley/**/*.py
      - name: Run typechecker
        run: python3 -m mypy wheatley --pretty --disallow-incomplete-defs --disallow-untyped-defs
      - name: Run unit tests
        run: python3 -m pytest
      - name: Run integration tests
        run: ./doctests
      - name: Run fuzzer
        run: ./fuzz
