name: "Testing/Linting/Fuzzing"

on:
  pull_request:
    branches:
      - master
      - release/*
  push:
    branches:
      - master
      - release/*
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          pip3 install setuptools
          pip3 install -r requirements.txt
      - name: Run linter
        run: python3 run-checks.py --lint
      - name: Run typechecker
        run: python3 run-checks.py --type-check
      - name: Run unit tests
        run: python3 run-checks.py --unit-test
      - name: Run integration tests
        run: python3 run-checks.py --doc-test
      - name: Run fuzzer
        run: python3 run-checks.py --fuzz
