name: "Testing/Linting/Fuzzing"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install setuptools pytest pylint
      - name: Run linter
        run: python3 -m pylint wheatley/**/*.py
      - name: Run tests
        run: python3 -m pytest
      - name: Run fuzzer
        run: ./fuzz
